// By Nahuel (vers1ons archive, web-export). Partners stay anonymous.
import type { DiagramSpec } from "../types";

export const distribution: DiagramSpec = {
  id: "distribution",
  eyebrow: "vers1ons · distribution",
  title: "From one click to every store",
  subtitle: "Nothing is written until every check passes, and every hop after that is a step that can resume on its own.",
  columns: 4,
  nodes: [
    {
      id: "wizard",
      title: "Release wizard",
      body: ["Track · Contributors · Release", "Cover · Review"],
      detail: "Five steps. When the track comes from a published license, its contributors and splits arrive locked, so a release can't contradict what was signed.",
      col: 1,
      row: 1,
    },
    {
      id: "gate",
      title: "Refuses before it writes",
      body: ["ownership", "rights scope from the license", "release timing", "payout readiness", "nothing already in flight"],
      detail: "Every check runs before the database is touched. A refusal comes back as a sentence the artist can act on, not a field name.",
      col: 2,
      row: 1,
    },
    {
      id: "tx",
      title: "One transaction · Postgres",
      body: ["release job", "rights grants up the chain", "what gets dispatched"],
      detail: "The job, the rights it creates for everyone upstream, and the dispatch commit together or not at all.",
      col: 2,
      row: 2,
    },
    {
      id: "job",
      title: "Durable job · Inngest",
      steps: [
        { id: "ids", label: "Issue release identifiers" },
        { id: "setup", label: "Set up the release" },
        { id: "stage", label: "Stage audio + art" },
        { id: "assemble", label: "Assemble metadata" },
        { id: "deliver", label: "Deliver to stores" },
        { id: "confirm", label: "Wait for confirmation", detail: "The job sleeps, for days if it has to, until the partner's signed confirmation wakes it." },
      ],
      detail: "Each step is resumable. A crash or a partner timeout replays from the last finished step, never from the top.",
      col: 3,
      row: 1,
      rowSpan: 2,
    },
    {
      id: "registry",
      zone: "partner",
      kind: "external",
      title: "Identifier registry",
      body: ["issues the codes stores require"],
      detail: "A registry partner issues the release and recording identifiers. Kept anonymous on purpose.",
      col: 4,
      row: 1,
    },
    {
      id: "storage",
      kind: "external",
      title: "Object storage",
      body: ["normalized audio", "cover art"],
      detail: "Media is normalized once and staged where the delivery partner can pull it.",
      col: 4,
      row: 2,
    },
    {
      id: "partner",
      zone: "partner",
      kind: "store",
      title: "Delivery partner",
      body: ["→ Spotify, Apple Music, TikTok…"],
      detail: "One delivery per route. Some stores only travel together, so the picker groups them instead of offering switches we can't honor.",
      col: 4,
      row: 3,
    },
    {
      id: "live",
      title: "Live status",
      body: ["every step → a live channel", "the wizard updates, no polling"],
      detail: "Each step writes its progress and pushes it to the artist's open tab.",
      col: 2,
      row: 3,
    },
  ],
  edges: [
    { from: "wizard", to: "gate", label: "submit", tone: "accent" },
    { from: "gate", to: "tx", label: "all pass", tone: "accent" },
    { from: "tx", to: "job.ids", label: "dispatch", tone: "accent" },
    { from: "job.ids", to: "registry", label: "codes", tone: "muted" },
    { from: "job.stage", to: "storage", label: "stage", tone: "muted" },
    { from: "job.deliver", to: "partner", label: "deliver", tone: "accent" },
    { from: "partner", to: "job.confirm", label: "confirmed", tone: "money", dashed: true },
    { from: "job.confirm", to: "live", label: "progress", tone: "muted", dashed: true },
  ],
  runs: {
    release: {
      label: "Run a release",
      steps: [
        { nodes: ["wizard"], log: "artist submits “Night Swim” · 1 track · 16 stores" },
        { nodes: ["gate"], edges: [["wizard", "gate"]], log: "5 checks passed · nothing written yet", tone: "accent" },
        { nodes: ["tx"], edges: [["gate", "tx"]], log: "1 transaction: job + rights grants + dispatch" },
        { nodes: ["job.ids", "registry"], edges: [["tx", "job.ids"], ["job.ids", "registry"]], log: "identifiers issued" },
        { nodes: ["job.setup", "live"], edges: [["job.confirm", "live"]], log: "release set up · artist's tab shows 2/6" },
        { nodes: ["job.stage", "storage"], edges: [["job.stage", "storage"]], log: "audio normalized · art staged" },
        { nodes: ["job.assemble"], log: "metadata assembled · fingerprinted" },
        { nodes: ["job.deliver", "partner"], edges: [["job.deliver", "partner"]], log: "delivered on every route" },
        { nodes: ["job.confirm"], log: "sleeping until the partner confirms…", ms: 1400 },
        { nodes: ["job.confirm", "live"], edges: [["partner", "job.confirm"]], log: "confirmation received · status: Delivered", tone: "money" },
      ],
    },
    timeout: {
      label: "Partner times out",
      steps: [
        { nodes: ["gate", "tx"], edges: [["wizard", "gate"], ["gate", "tx"]], log: "checks passed · committed" },
        { nodes: ["job.ids", "job.setup", "job.stage", "job.assemble"], edges: [["tx", "job.ids"]], log: "steps 1–4 finished" },
        { nodes: ["job.deliver", "partner"], edges: [["job.deliver", "partner"]], log: "partner timed out", tone: "warn" },
        { nodes: ["job.deliver"], log: "retrying with backoff…", tone: "warn", ms: 1400 },
        { nodes: ["job.deliver", "partner"], edges: [["job.deliver", "partner"]], log: "replayed from step 5 · steps 1–4 not repeated", tone: "accent" },
        { nodes: ["job.confirm", "live"], edges: [["partner", "job.confirm"]], log: "confirmed · status: Delivered", tone: "money" },
      ],
    },
    refused: {
      label: "License doesn't cover a store",
      steps: [
        { nodes: ["wizard"], log: "artist picks every store, including Spotify" },
        { nodes: ["gate"], edges: [["wizard", "gate"]], log: "rights scope: this license excludes Spotify", tone: "warn" },
        { nodes: ["wizard"], log: "nothing written · the picker shows why, per store", tone: "accent" },
      ],
    },
  },
};
