// By Nahuel (vers1ons archive, web-export: lineage.ts). Partners stay anonymous.
import type { DiagramSpec } from "../types";

export const licensing: DiagramSpec = {
  id: "licensing",
  eyebrow: "vers1ons · rights + drops",
  title: "Every remix stays traceable to its original",
  subtitle: "Works, licenses and drops share one graph. Rights and royalties travel with each derivative, however deep the chain goes.",
  columns: 4,
  nodes: [
    {
      id: "original",
      zone: "work",
      title: "Original",
      body: ["song · tracks · stems"],
      detail: "A work owns its recordings and stems. A remix is a work too, which is what lets the chain go deeper than one level.",
      col: 1,
      row: 1,
    },
    {
      id: "listing",
      zone: "marketplace",
      title: "Listing",
      body: ["license terms + price", "where a remix may release"],
      detail: "The licensor sets the terms once. They're frozen into every purchase, so later edits can't rewrite what a buyer already signed.",
      col: 2,
      row: 1,
    },
    {
      id: "purchase",
      zone: "money",
      title: "Purchase · Stripe",
      body: ["agreement signed first", "then payment"],
      detail: "Money never moves before the signature. Card, platform credit, or both.",
      col: 3,
      row: 1,
    },
    {
      id: "grant",
      zone: "rights",
      title: "Rights grant",
      body: ["what the buyer may do", "points at the grant it came from"],
      detail: "Each grant references its source grant, so rights resolve up the chain without copying them.",
      col: 4,
      row: 1,
    },
    {
      id: "remix",
      zone: "work",
      title: "Remix",
      body: ["a new work", "parent → original · root → original"],
      detail: "Lineage is recorded when the remix is saved, not inferred later from a title.",
      col: 4,
      row: 2,
    },
    {
      id: "drop",
      zone: "drop",
      title: "Drop entry",
      body: ["submitted · heard · starred", "host picks winners"],
      detail: "The host reviews entries on one page: who's been heard, what's been starred, then announces selections.",
      col: 3,
      row: 2,
    },
    {
      id: "window",
      zone: "drop",
      title: "Release window",
      body: ["refused before it opens"],
      detail: "Timing is enforced server-side at purchase, submission and distribution, not hidden in the UI.",
      col: 2,
      row: 2,
    },
    {
      id: "royalties",
      zone: "money",
      title: "Royalties up the chain",
      body: ["the remix earns", "the original's share flows back"],
      detail: "Each sale of a derivative pays everyone upstream according to the grants it inherited.",
      col: 1,
      row: 2,
    },
  ],
  edges: [
    { from: "original", to: "listing", label: "listed", tone: "muted" },
    { from: "listing", to: "purchase", label: "bought", tone: "accent" },
    { from: "purchase", to: "grant", label: "issues", tone: "accent" },
    { from: "grant", to: "remix", label: "made under", tone: "accent" },
    { from: "remix", to: "drop", label: "entered", tone: "muted" },
    { from: "drop", to: "window", label: "selected", tone: "muted" },
    { from: "window", to: "royalties", label: "released", tone: "money" },
    { from: "royalties", to: "original", label: "share back", tone: "money", dashed: true },
  ],
  runs: {
    remix: {
      label: "Run a remix",
      short: "A remix",
      steps: [
        { nodes: ["original", "listing"], edges: [["original", "listing"]], log: "“Bobby” is listed · remixes may release on 16 stores" },
        { nodes: ["purchase"], edges: [["listing", "purchase"]], log: "a fan signs the agreement, then pays", tone: "accent" },
        { nodes: ["grant"], edges: [["purchase", "grant"]], log: "grant issued · scoped to the listing's stores" },
        { nodes: ["remix"], edges: [["grant", "remix"]], log: "remix saved as a work · parent and root: “Bobby”" },
        { nodes: ["drop"], edges: [["remix", "drop"]], log: "entered in the drop · host stars it" },
        { nodes: ["window"], edges: [["drop", "window"]], log: "selected · releases when the window opens" },
        { nodes: ["royalties", "original"], edges: [["window", "royalties"], ["royalties", "original"]], log: "remix earns · the original's share flows back", tone: "money" },
      ],
    },
    early: {
      label: "Drop not open yet",
      short: "Not open yet",
      steps: [
        { nodes: ["listing"], log: "a fan opens the drop before its start date" },
        { nodes: ["purchase"], edges: [["listing", "purchase"]], log: "purchase refused before any payment", tone: "warn" },
        { nodes: ["window"], log: "the page shows the countdown instead", tone: "accent" },
      ],
    },
    scope: {
      label: "Store the license doesn't allow",
      short: "Wrong store",
      steps: [
        { nodes: ["listing"], log: "the licensor allows Spotify and Apple Music only" },
        { nodes: ["grant"], edges: [["listing", "purchase"], ["purchase", "grant"]], log: "the grant carries that scope" },
        { nodes: ["remix"], edges: [["grant", "remix"]], log: "a remix of the remix inherits it, one grant further down" },
        { nodes: ["window"], log: "release to another store refused · same check in the API, the wizard and delivery", tone: "warn" },
      ],
    },
  },
};
