// From Nahuel's account of how Sheets works. Partners stay anonymous.
import type { DiagramSpec } from "../types";

export const licensingSheets: DiagramSpec = {
  id: "licensing-sheets",
  eyebrow: "vers1ons · licensing · sheets",
  title: "A free tool that brings artists in",
  subtitle: "People searching for a split sheet find a free one with no account. They can leave with a PDF, or bring it into vers1ons, where collecting everyone's signature is paid, and the signed splits become a license.",
  columns: 4,
  nodes: [
    {
      id: "search",
      zone: "search",
      kind: "external",
      title: "A search",
      body: ["how do I make a split sheet?"],
      detail: "Sheets lives on its own subdomain, so it can be found by people who've never heard of vers1ons.",
      col: 1,
      row: 1,
    },
    {
      id: "sheet",
      zone: "satellite",
      title: "Sheets app",
      body: ["sheets.vers1ons.com", "no account", "splits to 100%"],
      detail: "One question per screen: the song, who's on it, what they did, then both sides split to 100%. Nothing is stored until someone saves; an unsaved sheet waits in Redis behind a one-time code.",
      col: 2,
      row: 1,
    },
    {
      id: "done",
      zone: "satellite",
      title: "Done",
      body: ["download it", "or bring it in"],
      detail: "The last screen offers both, side by side.",
      col: 3,
      row: 1,
    },
    {
      id: "pdf",
      title: "Free PDF",
      body: ["a regular split sheet"],
      detail: "Branded, two pages, with a line for each signature. Free.",
      col: 4,
      row: 1,
    },
    {
      id: "pay",
      zone: "money",
      title: "Pay to sign",
      body: ["Stripe", "another source of revenue"],
      detail: "Saving is free. Having every signature collected is what's paid.",
      col: 3,
      row: 2,
    },
    {
      id: "sign",
      zone: "rights",
      title: "Signatures",
      body: ["a link for each party", "bound to the exact text"],
      detail: "Sending freezes a version. Each person signs that version; an edit makes a new one and supersedes the open request.",
      col: 2,
      row: 2,
    },
    {
      id: "listing",
      zone: "vers1ons",
      title: "A license",
      body: ["the signed splits", "become the listing's"],
      detail: "The song arrives on vers1ons with its contributors and splits agreed, ready to be licensed.",
      col: 1,
      row: 2,
    },
  ],
  edges: [
    { from: "search", to: "sheet", label: "finds", tone: "muted" },
    { from: "sheet", to: "done", label: "balanced", tone: "accent" },
    { from: "done", to: "pdf", label: "download", tone: "muted" },
    { from: "done", to: "pay", label: "bring it in", tone: "accent" },
    { from: "pay", to: "sign", label: "paid", tone: "money" },
    { from: "sign", to: "listing", label: "all signed", tone: "accent" },
  ],
  runs: {
    into: {
      label: "Into vers1ons",
      short: "Into vers1ons",
      steps: [
        { nodes: ["search"], log: "someone searches for a split sheet" },
        { nodes: ["sheet"], edges: [["search", "sheet"]], log: "lands on sheets.vers1ons.com · no account" },
        { nodes: ["sheet"], log: "2 contributors · both sides at 100%" },
        { nodes: ["done"], edges: [["sheet", "done"]], log: "brings it into vers1ons" },
        { nodes: ["pay"], edges: [["done", "pay"]], log: "pays to have the signatures collected", tone: "money" },
        { nodes: ["sign"], edges: [["pay", "sign"]], log: "each party signs from their own link" },
        { nodes: ["listing"], edges: [["sign", "listing"]], log: "all signed · ready to become a license", tone: "accent" },
      ],
    },
    pdf: {
      label: "Just the PDF",
      short: "PDF",
      steps: [
        { nodes: ["sheet"], edges: [["search", "sheet"]], log: "a split sheet, built with no account" },
        { nodes: ["done"], edges: [["sheet", "done"]], log: "done" },
        { nodes: ["pdf"], edges: [["done", "pdf"]], log: "downloads the PDF, free", tone: "accent" },
      ],
    },
    edit: {
      label: "A split changes after sending",
      short: "An edit",
      steps: [
        { nodes: ["sign"], edges: [["pay", "sign"]], log: "sent for signatures · one person has signed" },
        { nodes: ["sheet"], log: "a split is changed", tone: "warn" },
        { nodes: ["sign"], log: "a new version · the open request is superseded", tone: "warn" },
        { nodes: ["sign", "listing"], edges: [["sign", "listing"]], log: "everyone signs the new version", tone: "accent" },
      ],
    },
  },
};
