// From Nahuel's account of how a drop works. Partners stay anonymous.
import type { DiagramSpec } from "../types";

export const licensingDrops: DiagramSpec = {
  id: "licensing-drops",
  eyebrow: "vers1ons · licensing · drops",
  title: "A remix contest where no one leaves a loser",
  subtitle: "The license is the entry fee. Every entrant ends up with a remix they're cleared to release, the winners get the prizes, and the original artist earns on all of it.",
  columns: 4,
  nodes: [
    {
      id: "drop",
      zone: "label · artist",
      title: "Drop created",
      body: ["its own rules and license", "submit, judge, release windows"],
      detail: "An established label or artist sets up the drop: the stems, the license, the prizes and the dates.",
      col: 1,
      row: 1,
    },
    {
      id: "page",
      zone: "marketplace",
      title: "Drop page",
      body: ["licenses on sale", "a limited number"],
      detail: "One design for the public and in-app pages. If anything here conflicts with the agreement, the agreement wins.",
      col: 2,
      row: 1,
    },
    {
      id: "buy",
      zone: "producer",
      title: "Buy to enter",
      body: ["agreement signed, then paid", "the license is the entry fee"],
      detail: "The artist is paid for every license sold, whoever wins.",
      col: 3,
      row: 1,
    },
    {
      id: "grant",
      zone: "rights",
      title: "Rights granted",
      body: ["licensed before a note is made"],
      detail: "The purchase is a real license, so every entry is cleared the moment it's made. Release terms are frozen at purchase.",
      col: 4,
      row: 1,
    },
    {
      id: "submit",
      zone: "producer",
      title: "Submit",
      body: ["inside the window", "a new work, pointing at the original"],
      detail: "The windows are enforced on the server, at purchase, at submission and at release, not just hidden in the page.",
      col: 4,
      row: 2,
    },
    {
      id: "judge",
      zone: "label · artist",
      title: "Judging",
      body: ["played · starred · picked"],
      detail: "The host sees which entries they haven't heard yet, then announces the winners.",
      col: 3,
      row: 2,
    },
    {
      id: "release",
      title: "Distribute",
      body: ["winners, and everyone else", "once the release window opens"],
      detail: "A drop can hold remixes back to a date. After that, every licensed entry can go to socials and stores.",
      col: 2,
      row: 2,
    },
    {
      id: "royalties",
      zone: "money",
      title: "Royalties",
      body: ["the remixer earns", "so does the original artist"],
      detail: "Each release pays everyone upstream by the grant it was made under.",
      col: 1,
      row: 2,
    },
  ],
  edges: [
    { from: "drop", to: "page", label: "opens", tone: "muted" },
    { from: "page", to: "buy", label: "bought", tone: "accent" },
    { from: "buy", to: "grant", label: "issues", tone: "accent" },
    { from: "grant", to: "submit", label: "entered", tone: "accent" },
    { from: "submit", to: "judge", label: "heard", tone: "muted" },
    { from: "judge", to: "release", label: "prizes", tone: "accent" },
    { from: "release", to: "royalties", label: "streams", tone: "money" },
    { from: "royalties", to: "drop", label: "share back", tone: "money", dashed: true },
  ],
  runs: {
    enter: {
      label: "Enter a drop",
      short: "Enter",
      steps: [
        { nodes: ["drop"], log: "a label opens a drop on “Bobby” · 100 licenses" },
        { nodes: ["page"], edges: [["drop", "page"]], log: "the drop page goes live" },
        { nodes: ["buy"], edges: [["page", "buy"]], log: "a producer signs, then pays · the artist is paid", tone: "accent" },
        { nodes: ["grant"], edges: [["buy", "grant"]], log: "licensed · cleared to release" },
        { nodes: ["submit"], edges: [["grant", "submit"]], log: "remix submitted inside the window" },
        { nodes: ["judge"], edges: [["submit", "judge"]], log: "played, starred · picked as a winner", tone: "accent" },
        { nodes: ["release"], edges: [["judge", "release"]], log: "prize awarded · released to stores" },
        { nodes: ["royalties", "drop"], edges: [["release", "royalties"], ["royalties", "drop"]], log: "the remixer earns · the original artist too", tone: "money" },
      ],
    },
    noloser: {
      label: "Not a winner",
      short: "Not picked",
      steps: [
        { nodes: ["submit"], edges: [["grant", "submit"]], log: "remix submitted" },
        { nodes: ["judge"], edges: [["submit", "judge"]], log: "heard, not picked this time" },
        { nodes: ["release"], edges: [["judge", "release"]], log: "still licensed · released once the window opens", tone: "accent" },
        { nodes: ["royalties", "drop"], edges: [["release", "royalties"], ["royalties", "drop"]], log: "it earns like any other remix", tone: "money" },
      ],
    },
    early: {
      label: "Drop not open yet",
      short: "Not open",
      steps: [
        { nodes: ["page"], log: "a producer opens the drop before its start date" },
        { nodes: ["buy"], edges: [["page", "buy"]], log: "purchase refused, before any payment", tone: "warn" },
        { nodes: ["page"], log: "the page shows the countdown instead", tone: "accent" },
      ],
    },
  },
};
