// From Nahuel's account of how a listing works. Partners stay anonymous.
import type { DiagramSpec } from "../types";

export const licensingListings: DiagramSpec = {
  id: "licensing-listings",
  eyebrow: "vers1ons · licensing · listings",
  title: "From an upload to royalties, and round again",
  subtitle: "The seller sets the terms once. Every purchase grants rights that point back to where they came from, so a remix can be listed and bought in turn, and royalties find their way up the chain.",
  columns: 4,
  nodes: [
    {
      id: "original",
      zone: "seller",
      title: "Original work",
      body: ["uploaded with its contributors", "and splits"],
      detail: "The artist uploads the song, says who wrote and recorded it, and splits both sides to 100%.",
      col: 1,
      row: 1,
    },
    {
      id: "terms",
      zone: "seller",
      title: "License terms",
      body: ["price · how many", "remixes of remixes", "where remixes may release"],
      detail: "Each term is a field with a plain summary beside it. The licensor signs with their legal name before it goes live.",
      col: 2,
      row: 1,
    },
    {
      id: "listing",
      zone: "marketplace",
      title: "Marketplace listing",
      body: ["the song on one side", "the license on the other"],
      detail: "Once live, the terms are frozen into every purchase: a later edit can't rewrite what a buyer already signed.",
      col: 3,
      row: 1,
    },
    {
      id: "purchase",
      zone: "buyer",
      title: "Purchase",
      body: ["agreement signed first", "then payment"],
      detail: "Money never moves before the signature.",
      col: 4,
      row: 1,
    },
    {
      id: "grant",
      zone: "rights",
      title: "Rights granted",
      body: ["what the buyer may do", "points at the grant above it"],
      detail: "Each grant references its source, so rights resolve up the chain without being copied.",
      col: 4,
      row: 2,
    },
    {
      id: "remix",
      zone: "buyer",
      title: "Remix",
      body: ["a new work", "its parent and root recorded"],
      detail: "A remix is a work too, so it can be listed and licensed in turn: a remix of a remix of a remix.",
      col: 3,
      row: 2,
    },
    {
      id: "release",
      title: "Distribute",
      body: ["only to the stores", "the license allows"],
      detail: "The same check decides it in the API, the release wizard and the delivery worker.",
      col: 2,
      row: 2,
    },
    {
      id: "royalties",
      zone: "money",
      title: "Royalties",
      body: ["the remix earns", "every share up the chain is paid"],
      detail: "Each sale and stream pays everyone upstream by the grants the remix inherited.",
      col: 1,
      row: 2,
    },
  ],
  edges: [
    { from: "original", to: "terms", label: "upload", tone: "muted" },
    { from: "terms", to: "listing", label: "publish", tone: "accent" },
    { from: "listing", to: "purchase", label: "bought", tone: "accent" },
    { from: "purchase", to: "grant", label: "issues", tone: "accent" },
    { from: "grant", to: "remix", label: "made under", tone: "accent" },
    { from: "remix", to: "listing", label: "listed too", tone: "accent", dashed: true },
    { from: "remix", to: "release", label: "release", tone: "muted" },
    { from: "release", to: "royalties", label: "streams", tone: "money" },
    { from: "royalties", to: "original", label: "share back", tone: "money", dashed: true },
  ],
  runs: {
    sale: {
      label: "Run a sale",
      short: "A sale",
      steps: [
        { nodes: ["original"], log: "“Night Swim” uploaded · splits at 100%" },
        { nodes: ["terms"], edges: [["original", "terms"]], log: "terms set · remixes may release on 16 stores" },
        { nodes: ["listing"], edges: [["terms", "listing"]], log: "signed and published to the marketplace", tone: "accent" },
        { nodes: ["purchase"], edges: [["listing", "purchase"]], log: "a producer signs the agreement, then pays", tone: "accent" },
        { nodes: ["grant"], edges: [["purchase", "grant"]], log: "rights granted · seller to buyer" },
        { nodes: ["remix"], edges: [["grant", "remix"]], log: "remix saved · parent and root: “Night Swim”" },
        { nodes: ["release"], edges: [["remix", "release"]], log: "distributed to the stores the license allows" },
        { nodes: ["royalties", "original"], edges: [["release", "royalties"], ["royalties", "original"]], log: "the remix earns · the original's share flows back", tone: "money" },
      ],
    },
    chain: {
      label: "A remix of a remix",
      short: "The chain",
      steps: [
        { nodes: ["remix"], log: "the remix is a work of its own" },
        { nodes: ["listing"], edges: [["remix", "listing"]], log: "its producer lists it, with their own terms", tone: "accent" },
        { nodes: ["purchase"], edges: [["listing", "purchase"]], log: "another producer buys a license to the remix" },
        { nodes: ["grant"], edges: [["purchase", "grant"]], log: "new grant · points at the grant above it" },
        { nodes: ["remix"], edges: [["grant", "remix"]], log: "a remix of a remix · root still “Night Swim”" },
        { nodes: ["release"], edges: [["remix", "release"]], log: "released · scope inherited from both licenses" },
        { nodes: ["royalties", "original"], edges: [["release", "royalties"], ["royalties", "original"]], log: "the remixer, the first remixer and the original all get paid", tone: "money" },
      ],
    },
    scope: {
      label: "Store the license doesn't allow",
      short: "Wrong store",
      steps: [
        { nodes: ["terms"], log: "the licensor allows Spotify and Apple Music only" },
        { nodes: ["grant"], edges: [["listing", "purchase"], ["purchase", "grant"]], log: "the grant carries that scope" },
        { nodes: ["remix"], edges: [["grant", "remix"]], log: "a remix of the remix inherits it" },
        { nodes: ["release"], edges: [["remix", "release"]], log: "release to another store refused, before anything is written", tone: "warn" },
      ],
    },
  },
};
