// From Nahuel's account of the purchase flow (his UI and UX; the signing,
// payments and rights grant behind it are the team's), checked against his
// PRs #2112, #2237, #2813 and #2901. Partners stay anonymous.
import type { DiagramSpec } from "../types";

export const purchasing: DiagramSpec = {
  id: "purchasing",
  eyebrow: "vers1ons · purchasing",
  title: "A license, as easy as a song",
  subtitle: "One flow on a phone or a desktop. See the license, sign it, pay, and get your files. Nothing the license needs is cut to make it shorter.",
  columns: 4,
  nodes: [
    {
      id: "listing",
      zone: "buyer",
      title: "Listing",
      body: ["price and terms up front", "royalties in one line"],
      detail: "The song on one side, the license you're buying on the other, with the price and Purchase at the top. On a phone the price and Purchase stay fixed at the bottom.",
      col: 1,
      row: 1,
    },
    {
      id: "summary",
      zone: "buyer",
      title: "Order summary",
      body: ["what you're getting", "credit applied first"],
      detail: "The files, the licensor, where a remix can be released, the fee and the total, before anything is signed.",
      col: 2,
      row: 1,
    },
    {
      id: "agreement",
      zone: "rights",
      title: "Agreement",
      body: ["read and sign", "its own terms, kept"],
      detail: "The buyer reads and signs before payment opens. Each signed agreement keeps its own terms, so a later price change only affects future sales.",
      col: 3,
      row: 1,
    },
    {
      id: "payment",
      zone: "money",
      title: "Payment",
      body: ["card, credit or both", "opens once signed"],
      detail: "Once the agreement is signed it folds away and payment opens below it. Credit covers what it can and the card pays the rest.",
      col: 4,
      row: 1,
    },
    {
      id: "sale",
      title: "Sale · Stripe",
      body: ["settled once"],
      detail: "Built by the team. The sale settles once, and only then is the license granted.",
      col: 4,
      row: 2,
    },
    {
      id: "grant",
      zone: "rights",
      title: "Rights grant",
      body: ["the remix license", "and the signed PDF"],
      detail: "The purchase becomes a license on the rights chain, and the signed agreement is rendered as a PDF.",
      col: 3,
      row: 2,
    },
    {
      id: "files",
      zone: "buyer",
      title: "Your files",
      body: ["master and agreement", "stems when uploaded"],
      detail: "Right after paying you get the master recording, the signed agreement, and the stems when the artist uploaded them. One at a time or all at once.",
      col: 2,
      row: 2,
    },
    {
      id: "library",
      zone: "buyer",
      title: "Library",
      body: ["every purchase", "the receipt as a dialog"],
      detail: "Every license stays in the library with its audio, stems and contract. On the song's page, View Purchase opens a small receipt instead of a whole page.",
      col: 1,
      row: 2,
    },
  ],
  edges: [
    { from: "listing", to: "summary", label: "purchase", tone: "accent" },
    { from: "summary", to: "agreement", label: "continue" },
    { from: "agreement", to: "payment", label: "signed", tone: "accent" },
    { from: "payment", to: "sale", label: "paid", tone: "money" },
    { from: "sale", to: "grant", label: "settles", tone: "accent" },
    { from: "grant", to: "files", label: "licensed" },
    { from: "files", to: "library", label: "kept" },
  ],
  runs: {
    buy: {
      label: "Buy a license",
      short: "Buy",
      steps: [
        { nodes: ["listing"], log: "Ada opens “Golden Static” · $60, terms and royalties up front" },
        { nodes: ["summary"], edges: [["listing", "summary"]], log: "order summary · master, 2 stems · $69 with the fee" },
        { nodes: ["agreement"], edges: [["summary", "agreement"]], log: "she reads and signs the agreement", tone: "accent" },
        { nodes: ["payment"], edges: [["agreement", "payment"]], log: "it folds away · payment opens below it", tone: "money" },
        { nodes: ["sale", "grant"], edges: [["payment", "sale"], ["sale", "grant"]], log: "paid · settled once · the license is granted", tone: "accent" },
        { nodes: ["files"], edges: [["grant", "files"]], log: "You're licensed · master, stems and the signed PDF" },
        { nodes: ["library"], edges: [["files", "library"]], log: "it's in her library, with the receipt one click away" },
      ],
    },
    unsigned: {
      label: "Try to pay before signing",
      short: "Unsigned",
      steps: [
        { nodes: ["summary", "agreement"], edges: [["summary", "agreement"]], log: "the agreement isn't signed yet" },
        { nodes: ["payment"], log: "payment stays closed · “Sign the agreement to continue”", tone: "warn" },
        { nodes: ["agreement", "payment"], edges: [["agreement", "payment"]], log: "signed · now payment opens", tone: "accent" },
      ],
    },
    repriced: {
      label: "The artist changes the price later",
      short: "Re-priced",
      steps: [
        { nodes: ["grant"], log: "Ada's license was signed at $60" },
        { nodes: ["listing"], log: "the artist re-prices the listing to $80", tone: "warn" },
        { nodes: ["agreement"], log: "her signed agreement keeps its own terms · nothing changes for her", tone: "accent" },
        { nodes: ["listing", "summary"], edges: [["listing", "summary"]], log: "the new price applies to future sales only" },
      ],
    },
    pdf: {
      label: "The signed PDF is still being made",
      short: "PDF",
      steps: [
        { nodes: ["sale", "grant"], edges: [["sale", "grant"]], log: "paid · the signed PDF is still rendering" },
        { nodes: ["library"], log: "the receipt waits for it, without a broken link", tone: "muted" },
        { nodes: ["files", "library"], edges: [["grant", "files"]], log: "the PDF is ready · the download appears", tone: "accent" },
      ],
    },
  },
};
