// From Nahuel's account of how money moves on vers1ons; the credit ledger
// from his archive spec (web-export: credit.ts). Partners stay anonymous.
import type { DiagramSpec } from "../types";

export const walletPayouts: DiagramSpec = {
  id: "wallet-payouts",
  eyebrow: "vers1ons · wallet & payouts",
  title: "Money follows the rights",
  subtitle: "A sale is split the way the license says, and each share goes to its owner: the artist, every contributor, and the original artist up the chain. Bank details are asked for only when someone withdraws.",
  columns: 4,
  nodes: [
    {
      id: "credit",
      zone: "money",
      title: "Credit ledger",
      body: ["a balance, not a coupon", "every change is a new row"],
      detail: "Grants, spends and reversals are rows in an append-only ledger; the balance is their sum. A giveaway is a real purchase, so the rights really transfer.",
      col: 1,
      row: 1,
    },
    {
      id: "checkout",
      zone: "buyer",
      title: "Checkout",
      body: ["credit, card, or both", "agreement signed first"],
      detail: "The buyer chooses how much credit to apply; the card covers only the rest. Fully covered by credit, there's no card form at all.",
      col: 2,
      row: 1,
    },
    {
      id: "sale",
      title: "Sale · Stripe",
      body: ["settled once"],
      detail: "A card sale settles from Stripe's event; a sale paid with credit alone has no charge to wait for, so it settles as its own event.",
      col: 3,
      row: 1,
    },
    {
      id: "split",
      zone: "rights",
      title: "Split by the license",
      body: ["recording and composition", "each side to 100%"],
      detail: "The shares come from the listing's signed splits, so the money can't disagree with the license.",
      col: 4,
      row: 1,
    },
    {
      id: "payees",
      zone: "rights",
      title: "Every rights holder",
      body: ["the artist", "each contributor", "the original, up the chain"],
      detail: "vers1ons pays each share directly. The artist no longer gets a lump sum to divide by hand.",
      col: 4,
      row: 2,
    },
    {
      id: "claim",
      zone: "email",
      title: "Claim by email",
      body: ["no account needed", "a new or existing account"],
      detail: "A contributor added only by email is told they have a share waiting. They can create an account, or connect the one they have, even under a different email, with a code sent to the claim address.",
      col: 3,
      row: 3,
    },
    {
      id: "wallet",
      title: "Wallet",
      body: ["what you've earned", "and from which sale"],
      detail: "Available and pending balances, credit kept apart (it can be spent, not withdrawn), and every earning line by song.",
      col: 2,
      row: 2,
    },
    {
      id: "withdraw",
      zone: "money",
      title: "Withdraw · Connect",
      body: ["bank details asked for here", "not at sign-up"],
      detail: "Sign-up has no bank step. Payout setup comes up where money moves: withdrawing, publishing for sale, distributing.",
      col: 1,
      row: 2,
    },
  ],
  edges: [
    { from: "credit", to: "checkout", label: "spend", tone: "money" },
    { from: "checkout", to: "sale", label: "paid", tone: "accent" },
    { from: "sale", to: "split", label: "settles", tone: "accent" },
    { from: "split", to: "payees", label: "shares", tone: "money" },
    { from: "payees", to: "wallet", label: "paid directly", tone: "money" },
    { from: "payees", to: "claim", label: "no account yet", tone: "muted", dashed: true },
    { from: "claim", to: "wallet", label: "claimed", tone: "accent", dashed: true },
    { from: "wallet", to: "withdraw", label: "withdraw", tone: "money" },
  ],
  runs: {
    sale: {
      label: "Run a sale",
      short: "A sale",
      steps: [
        { nodes: ["checkout"], log: "Ada buys a license to “Night Swim” · card" },
        { nodes: ["sale"], edges: [["checkout", "sale"]], log: "paid · settled once" },
        { nodes: ["split"], edges: [["sale", "split"]], log: "split by the listing's signed splits", tone: "accent" },
        { nodes: ["payees"], edges: [["split", "payees"]], log: "Cato's share, Mara's share, each paid directly", tone: "money" },
        { nodes: ["wallet"], edges: [["payees", "wallet"]], log: "Cato's wallet shows his share, by sale" },
        { nodes: ["withdraw"], edges: [["wallet", "withdraw"]], log: "he withdraws to his bank", tone: "money" },
      ],
    },
    claim: {
      label: "A contributor with no account",
      short: "Claim",
      steps: [
        { nodes: ["split", "payees"], edges: [["sale", "split"], ["split", "payees"]], log: "Mara was added by email · no account yet" },
        { nodes: ["claim"], edges: [["payees", "claim"]], log: "her share is held · she's emailed that it's waiting", tone: "accent" },
        { nodes: ["claim"], log: "she claims it: a new account, or one she already has" },
        { nodes: ["wallet"], edges: [["claim", "wallet"]], log: "it shows in her wallet, waiting for payouts to be set up" },
      ],
    },
    credit: {
      label: "Paid with credit",
      short: "Credit",
      steps: [
        { nodes: ["credit"], log: "Rook has $150 of platform credit" },
        { nodes: ["checkout"], edges: [["credit", "checkout"]], log: "credit covers all $69 · no card form", tone: "money" },
        { nodes: ["sale"], edges: [["checkout", "sale"]], log: "no charge to wait for · settles as its own event" },
        { nodes: ["split", "payees"], edges: [["sale", "split"], ["split", "payees"]], log: "a real sale: the rights transfer, every share is paid", tone: "accent" },
      ],
    },
    reversed: {
      label: "A credit sale that never completes",
      short: "Reversed",
      steps: [
        { nodes: ["credit", "checkout"], edges: [["credit", "checkout"]], log: "credit spent at checkout" },
        { nodes: ["sale"], edges: [["checkout", "sale"]], log: "the purchase fails", tone: "warn" },
        { nodes: ["credit"], log: "the spend is reversed in the same transaction · balance restored", tone: "accent" },
      ],
    },
  },
};
